export const contacts = [
  { id: "1", name: "Ariel Anderson", email: "ariel@email.com" },
  { id: "2", name: "Emily Johnson", email: "emily@email.com" },
  { id: "3", name: "Erick Brown", email: "erick@email.com" },
  { id: "4", name: "Sophia Davis", email: "sophia@email.com" },
  { id: "5", name: "David Wilson", email: "david@email.com" },
  { id: "6", name: "Barbara Taylor", email: "barbara@email.com" },
  { id: "7", name: "Felipe Moore", email: "felipe@email.com" },
  { id: "8", name: "Heloisa Clark", email: "heloisa@email.com" },
  { id: "9", name: "Joao Lee", email: "joao@email.com" },
  { id: "10", name: "Paola Harris", email: "paola@email.com" },
  { id: "11", name: "Vitor Walker", email: "vitor@email.com" },
  { id: "12", name: "Murillo Young", email: "murillo@email.com" },
  { id: "13", name: "Rhuan Lewis", email: "rhuan@email.com" },
  { id: "14", name: "Miguel Hall", email: "miguel@email.com" },
  { id: "15", name: "Gabriel Scott", email: "gabriel@email.com" },
  { id: "16", name: "Artur King", email: "artur@email.com" },
  { id: "17", name: "Fabricio Allen", email: "fabricio@email.com" },
  { id: "18", name: "Carlos Martin", email: "carlos@email.com" },
  { id: "19", name: "Daniela Wright", email: "daniela@email.com" },
  { id: "20", name: "Vicente Thompson", email: "vicente@email.com" },
]
